### ISSUE TITLE
Can I get a list of pronunciations for every char.

### ISSUE THREAD

**Issue by VShawn** [Cutano/Kawazu#1]
Hi, thanks for your nice work, but I'd like to get pronunciations one by one.

as`"今晩"`

`var result = await converter.Convert("今晩は", To.Romaji, Mode.Normal, RomajiSystem.Hepburn, "(", ")");`

Kawazu return `"komban"` now 

I wanna get a list `{"kom", "ban"}` for searching match purpose

is there any way to get this list?

**Comment by Cutano** [comment]
Sorry for my late reply, I'm kind of busy right now. I'll check this out as soon as possible :)

**Comment by Cutano** [comment]
The fact is, some of the Japanese words CAN NOT be divided to get pronunciations one by one.
For example, the word "景色" is written as "Keshiki" in Romaji, and they only pronounced like this when those two characters are together. You **CAN NOT** tear them apart because they pronounce different in each char, "Kei" and "Shiki".


I suggest you use the  `GetDivisions` method to get the list of Divisions.
The `GetDivisions` method of the `Converter` class returns the division lists of your sentence.
You can find the detailed guide at the "Advanced Usage Part" of [README](https://github.com/Cutano/Kawazu#advanced-usage).
Or you can just query the char one by one, but the result might be unprecise.


If you have any other questions, plz feel free to ask me :)

**Comment by VShawn** [comment]
Ahhh I see, will check the `GetDivisions`  Thx for reply.
